datasource:
  mysql:
    #JdbcUrl: jdbc:mysql://127.0.0.1:3306/javablog?useUnicode=true&characterEncoding=utf8&useSSL=false
    JdbcUrl: jdbc:mysql://127.0.0.1:3306/template?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #DriverClassName: com.mysql.jdbc.Driver
    DriverClassName: com.mysql.cj.jdbc.Driver
    Username: root
    Password: 123456
    useSSL: false
upload:
  uploadFolder: E:/uploadFolder/user
spring:
  servlet:
    multipart:
      max-file-size: 35MB  # 如果前端分块每10M一块，最后一块如果是19M，那么则会按19M上传，所以要设置大些
      maxRequestSize: 35MB